/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fbos.clientpkg;

/**
 *
 * @author Robin
 */
public class uiLog extends javax.swing.JFrame {

    /**
     * Creates new form uiLog
     */
    public uiLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uiLogLab = new javax.swing.JLabel();
        uiNameLab = new javax.swing.JLabel();
        uiPassLab = new javax.swing.JLabel();
        uiNameTF = new javax.swing.JTextField();
        uiPassTF = new javax.swing.JTextField();
        uiNewLab = new javax.swing.JLabel();
        uiLogButt = new javax.swing.JButton();
        uiRegButt = new javax.swing.JButton();
        uiIPAddLab = new javax.swing.JLabel();
        uiIPAddTF = new javax.swing.JTextField();
        uiIPAddButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uiLogLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiLogLab.setText("User Login");

        uiNameLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiNameLab.setText("User Name");

        uiPassLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiPassLab.setText("Password");

        uiNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiNameTFActionPerformed(evt);
            }
        });

        uiPassTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        uiNewLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiNewLab.setText("New User Registration");

        uiLogButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiLogButt.setText("Login");
        uiLogButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiLogButtActionPerformed(evt);
            }
        });

        uiRegButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiRegButt.setText("Registration");

        uiIPAddLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiIPAddLab.setText("IP Address");

        uiIPAddTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiIPAddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiIPAddTFActionPerformed(evt);
            }
        });

        uiIPAddButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiIPAddButt.setText("Enter");
        uiIPAddButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiIPAddButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uiNewLab)
                            .addComponent(uiLogLab)
                            .addComponent(uiRegButt)
                            .addComponent(uiIPAddLab)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uiPassLab)
                            .addComponent(uiNameLab))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uiIPAddButt)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(uiNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(uiPassTF, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(uiLogButt)
                                .addComponent(uiIPAddTF)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiIPAddLab)
                    .addComponent(uiIPAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uiIPAddButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(uiLogLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiNameLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiPassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiPassLab, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uiLogButt)
                .addGap(23, 23, 23)
                .addComponent(uiNewLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uiRegButt)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiNameTFActionPerformed

    private void uiLogButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiLogButtActionPerformed
        String uiName, uiPass;
        uiName = uiNameTF.getText();
        uiPass = uiPassTF.getText();
        
    }//GEN-LAST:event_uiLogButtActionPerformed

    private void uiIPAddButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiIPAddButtActionPerformed
        String uiIPAdd;
        uiIPAdd = uiIPAddTF.getText();
    }//GEN-LAST:event_uiIPAddButtActionPerformed

    private void uiIPAddTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiIPAddTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiIPAddTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new uiLog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton uiIPAddButt;
    private javax.swing.JLabel uiIPAddLab;
    private javax.swing.JTextField uiIPAddTF;
    private javax.swing.JButton uiLogButt;
    private javax.swing.JLabel uiLogLab;
    private javax.swing.JLabel uiNameLab;
    private javax.swing.JTextField uiNameTF;
    private javax.swing.JLabel uiNewLab;
    private javax.swing.JLabel uiPassLab;
    private javax.swing.JTextField uiPassTF;
    private javax.swing.JButton uiRegButt;
    // End of variables declaration//GEN-END:variables
}
