/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fbos.clientpkg;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Robin
 */
public class uiNewAccount extends javax.swing.JFrame {

    /**
     * Creates new form uiNewAccount
     */
    public uiNewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UINewPan = new javax.swing.JPanel();
        uiNameLab = new javax.swing.JLabel();
        uiUserTF = new javax.swing.JTextField();
        uiNameButt = new javax.swing.JButton();
        uiLogButt = new javax.swing.JButton();
        invalidLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UINewPan.setBorder(javax.swing.BorderFactory.createTitledBorder("New Account Page"));

        uiNameLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiNameLab.setText("Enter a unique user name");

        uiUserTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiUserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiUserTFActionPerformed(evt);
            }
        });

        uiNameButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiNameButt.setText("Enter user name if available");
        uiNameButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiNameButtActionPerformed(evt);
            }
        });

        uiLogButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiLogButt.setText("Exit Back To Login Page");
        uiLogButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiLogButtActionPerformed(evt);
            }
        });

        invalidLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout UINewPanLayout = new javax.swing.GroupLayout(UINewPan);
        UINewPan.setLayout(UINewPanLayout);
        UINewPanLayout.setHorizontalGroup(
            UINewPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UINewPanLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(UINewPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UINewPanLayout.createSequentialGroup()
                        .addComponent(uiUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(invalidLab, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uiNameLab)
                    .addGroup(UINewPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(uiLogButt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uiNameButt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        UINewPanLayout.setVerticalGroup(
            UINewPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UINewPanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(uiNameLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UINewPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalidLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uiNameButt)
                .addGap(37, 37, 37)
                .addComponent(uiLogButt)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UINewPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UINewPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiNameButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiNameButtActionPerformed
        String uiName;
        uiName = uiUserTF.getText();
        try {
            int nameIsValid = FBOSClient.FBOSServer.verifyName(uiName);
            if (nameIsValid !=1) {
                invalidLab.setText("Name allready in use.");
            }else{
                uiUserEdit newUserFrame = new uiUserEdit();
                newUserFrame.UserName=uiName;
                newUserFrame.setVisible(true);
                this.dispose();
            }
        } catch (RemoteException ex) {
            Logger.getLogger(uiNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uiNameButtActionPerformed

    private void uiLogButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiLogButtActionPerformed
        JFrame newUserFrame = new uiLog();
   //     this.setVisible(false);
        newUserFrame.setVisible(true);
        this.dispose();
   //     uiLog.setVisible(true);
        
   //     toFront();
    }//GEN-LAST:event_uiLogButtActionPerformed

    private void uiUserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiUserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiUserTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new uiNewAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UINewPan;
    private javax.swing.JLabel invalidLab;
    private javax.swing.JButton uiLogButt;
    private javax.swing.JButton uiNameButt;
    private javax.swing.JLabel uiNameLab;
    private javax.swing.JTextField uiUserTF;
    // End of variables declaration//GEN-END:variables
}
