/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fbos.clientpkg;

/**
 *
 * @author Robin
 */
public class uiNewAccount extends javax.swing.JFrame {

    /**
     * Creates new form uiNewAccount
     */
    public uiNewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UINewPan = new javax.swing.JPanel();
        uiNameLab = new javax.swing.JLabel();
        uiUserTF = new javax.swing.JTextField();
        uiNameButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UINewPan.setBorder(javax.swing.BorderFactory.createTitledBorder("New Account Page"));

        uiNameLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiNameLab.setText("Enter a unique user name");

        uiUserTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        uiNameButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiNameButt.setText("Enter user name if available");
        uiNameButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiNameButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UINewPanLayout = new javax.swing.GroupLayout(UINewPan);
        UINewPan.setLayout(UINewPanLayout);
        UINewPanLayout.setHorizontalGroup(
            UINewPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UINewPanLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(UINewPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uiNameButt)
                    .addComponent(uiUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiNameLab))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        UINewPanLayout.setVerticalGroup(
            UINewPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UINewPanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(uiNameLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uiUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uiNameButt)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UINewPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UINewPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiNameButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiNameButtActionPerformed
        String uiName;
        uiName = uiUserTF.getText();
    }//GEN-LAST:event_uiNameButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new uiNewAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UINewPan;
    private javax.swing.JButton uiNameButt;
    private javax.swing.JLabel uiNameLab;
    private javax.swing.JTextField uiUserTF;
    // End of variables declaration//GEN-END:variables
}
