/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fbos.clientpkg;

/**
 *
 * @author Robin
 */
public class uiWall extends javax.swing.JFrame {

    /**
     * Creates new form uiWall
     */
    public uiWall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uiFri1TF = new javax.swing.JTextField();
        uiFri2TF = new javax.swing.JTextField();
        uiFri3TF = new javax.swing.JTextField();
        uiFri4TF = new javax.swing.JTextField();
        uiFri5TF = new javax.swing.JTextField();
        uiFri6TF = new javax.swing.JTextField();
        uiFri7TF = new javax.swing.JTextField();
        uiFri8TF = new javax.swing.JTextField();
        uiFri9TF = new javax.swing.JTextField();
        uiFri10TF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        uiFriLab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uiWall1TA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        uiWall2TA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        uiWall3TA = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        uiWall4TA = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        uiWall5TA = new javax.swing.JTextArea();
        uiFri1Butt = new javax.swing.JButton();
        uiFri2Butt = new javax.swing.JButton();
        uiFri3Butt = new javax.swing.JButton();
        uiFri4Butt = new javax.swing.JButton();
        uiFri5Butt = new javax.swing.JButton();
        uiFri6Butt = new javax.swing.JButton();
        uiFri7Butt = new javax.swing.JButton();
        uiFri8Butt = new javax.swing.JButton();
        uiFri9Butt = new javax.swing.JButton();
        uiFri10Butt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uiPrevWallButt = new javax.swing.JButton();
        uiNextWallButt = new javax.swing.JButton();
        uiWallLab = new javax.swing.JLabel();
        uiWallProfButt = new javax.swing.JButton();
        uiWallSearchButt = new javax.swing.JButton();
        uiWallLogOutButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uiFri1TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiFri1TFActionPerformed(evt);
            }
        });

        uiFri2TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uiFri3TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uiFri4TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uiFri5TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uiFri6TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uiFri7TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uiFri8TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uiFri9TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uiFri10TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton1.setText("Previous");

        jButton2.setText("Next");

        uiFriLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiFriLab.setText("List of Friends");

        uiWall1TA.setColumns(20);
        uiWall1TA.setRows(5);
        jScrollPane1.setViewportView(uiWall1TA);

        uiWall2TA.setColumns(20);
        uiWall2TA.setRows(5);
        jScrollPane2.setViewportView(uiWall2TA);

        uiWall3TA.setColumns(20);
        uiWall3TA.setRows(5);
        jScrollPane3.setViewportView(uiWall3TA);

        uiWall4TA.setColumns(20);
        uiWall4TA.setRows(5);
        jScrollPane4.setViewportView(uiWall4TA);

        uiWall5TA.setColumns(20);
        uiWall5TA.setRows(5);
        jScrollPane5.setViewportView(uiWall5TA);

        uiFri1Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri1Butt.setText("1");

        uiFri2Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri2Butt.setText("2");

        uiFri3Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri3Butt.setText("3");

        uiFri4Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri4Butt.setText("4");

        uiFri5Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri5Butt.setText("5");

        uiFri6Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri6Butt.setText("6");

        uiFri7Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri7Butt.setText("7");

        uiFri8Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri8Butt.setText("8");

        uiFri9Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri9Butt.setText("9");

        uiFri10Butt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uiFri10Butt.setText("10");

        jLabel1.setText("Post on Friends Wall");

        uiPrevWallButt.setText("Previous");

        uiNextWallButt.setText("Next");

        uiWallLab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uiWallLab.setText("WALL");

        uiWallProfButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiWallProfButt.setText("EDIT PROFILE");
        uiWallProfButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiWallProfButtActionPerformed(evt);
            }
        });

        uiWallSearchButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiWallSearchButt.setText("SEARCH FOR A FRIEND");

        uiWallLogOutButt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uiWallLogOutButt.setText("LOG OUT");
        uiWallLogOutButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiWallLogOutButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uiWallProfButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uiWallSearchButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uiWallLogOutButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uiWallLab)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(uiPrevWallButt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uiNextWallButt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri2Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri3Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri4Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri5Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri6Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri6TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri7Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri7TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri8Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri8TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri9Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri9TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uiFri10Butt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiFri10TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uiFri1Butt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uiFriLab)
                            .addComponent(uiFri1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFriLab)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri1Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri2Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri3Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri4Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri5TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri5Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri6TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri6Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri7TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri7Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri8TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri8Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri9TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri9Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiFri10TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiFri10Butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uiWallLab)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uiWallProfButt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uiWallSearchButt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uiWallLogOutButt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uiNextWallButt)
                            .addComponent(uiPrevWallButt))))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiFri1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiFri1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiFri1TFActionPerformed

    private void uiWallProfButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiWallProfButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiWallProfButtActionPerformed

    private void uiWallLogOutButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiWallLogOutButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiWallLogOutButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiWall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiWall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiWall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiWall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new uiWall().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton uiFri10Butt;
    private javax.swing.JTextField uiFri10TF;
    private javax.swing.JButton uiFri1Butt;
    private javax.swing.JTextField uiFri1TF;
    private javax.swing.JButton uiFri2Butt;
    private javax.swing.JTextField uiFri2TF;
    private javax.swing.JButton uiFri3Butt;
    private javax.swing.JTextField uiFri3TF;
    private javax.swing.JButton uiFri4Butt;
    private javax.swing.JTextField uiFri4TF;
    private javax.swing.JButton uiFri5Butt;
    private javax.swing.JTextField uiFri5TF;
    private javax.swing.JButton uiFri6Butt;
    private javax.swing.JTextField uiFri6TF;
    private javax.swing.JButton uiFri7Butt;
    private javax.swing.JTextField uiFri7TF;
    private javax.swing.JButton uiFri8Butt;
    private javax.swing.JTextField uiFri8TF;
    private javax.swing.JButton uiFri9Butt;
    private javax.swing.JTextField uiFri9TF;
    private javax.swing.JLabel uiFriLab;
    private javax.swing.JButton uiNextWallButt;
    private javax.swing.JButton uiPrevWallButt;
    private javax.swing.JTextArea uiWall1TA;
    private javax.swing.JTextArea uiWall2TA;
    private javax.swing.JTextArea uiWall3TA;
    private javax.swing.JTextArea uiWall4TA;
    private javax.swing.JTextArea uiWall5TA;
    private javax.swing.JLabel uiWallLab;
    private javax.swing.JButton uiWallLogOutButt;
    private javax.swing.JButton uiWallProfButt;
    private javax.swing.JButton uiWallSearchButt;
    // End of variables declaration//GEN-END:variables
}
